url:        http://andymcfee.com
baseurl:    /
auto:       true

#pygments:    true
permalink:  /:year/:month/:title/
#paginate:    5
#paginate_file: posts.html

exclude:    README.md, sass, ideas.txt, config, Capfile, config.rb
markdown:   maruku


# RSS
name: andymcfee.com
description: Thoughts on all things web.
url: http://andymcfee.com